2022-11-09 09:44:12,566 Converting data/part200/in/kerala/2015/2015_103_011.pdf to img...
2022-11-09 09:44:20,707 Parsing first and last page data..
2022-11-09 09:44:24,172 Detecting and parsing data/part200/in/kerala/2015/2015_103_011.pdf boxes..
2022-11-09 09:44:24,173 Processing page 3
2022-11-09 09:44:59,718 Processing page 4
2022-11-09 09:45:36,012 Processing page 5
2022-11-09 09:46:13,865 Processing page 6
2022-11-09 09:46:51,271 Processing page 7
2022-11-09 09:47:29,595 Processing page 8
2022-11-09 09:48:06,386 Processing page 9
2022-11-09 09:48:45,081 Processing page 10
2022-11-09 09:49:22,395 Processing page 11
2022-11-09 09:50:00,499 Processing page 12
2022-11-09 09:50:38,655 Processing page 13
2022-11-09 09:51:15,804 Processing page 14
2022-11-09 09:51:54,728 Processing page 15
2022-11-09 09:52:32,653 Processing page 16
2022-11-09 09:53:10,448 Processing page 17
2022-11-09 09:53:47,674 Processing page 18
--- Logging error ---
Traceback (most recent call last):
  File "/home/t-9adar/.conda/envs/env38/lib/python3.8/logging/__init__.py", line 1084, in emit
    stream.write(msg + self.terminator)
UnicodeEncodeError: 'latin-1' codec can't encode character '\u201d' in position 47: ordinal not in range(256)
Call stack:
  File "/home/t-9adar/.conda/envs/env38/lib/python3.8/threading.py", line 890, in _bootstrap
    self._bootstrap_inner()
  File "/home/t-9adar/.conda/envs/env38/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/home/t-9adar/.conda/envs/env38/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/t-9adar/.conda/envs/env38/lib/python3.8/concurrent/futures/thread.py", line 80, in _worker
    work_item.run()
  File "/home/t-9adar/.conda/envs/env38/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "../parse_unsearchable_rolls/parser/parser.py", line 320, in get_data
    processed_box = self.process_boxes_text(text)
  File "../parse_unsearchable_rolls/parser/parser.py", line 149, in process_boxes_text
    result, last_key, is_splitted = self.columns_split(r, self.columns, result, last_key)
  File "../parse_unsearchable_rolls/parser/parser.py", line 255, in columns_split
    result, last_key, is_splitted = self.handle_separator_without_column(r, result, last_key)
  File "../parse_unsearchable_rolls/parser/parser.py", line 226, in handle_separator_without_column
    logging.warning(f'Split uncaught {r} {result}')
Message: "Split uncaught Algyenic\u201d PrOL>BO2IGIH OD OrderedDict([('number', '455'), ('id', 'KL/15/097/315664'), ('\u0d2a\u0d47\u0d30\u0d4d', '\u0d2e\u0d3f\u0d28\u0d3f'), ('\u0d35\u0d40\u0d1f\u0d4d\u0d1f\u0d41\u0d28\u0d2e\u0d4d\u0d2a\u0d30\u0d4d', '8/187 (14/179)')])"
Arguments: ()
2022-11-09 09:54:20,765 Split uncaught Algyenic\u201d PrOL>BO2IGIH OD OrderedDict([('number', '455'), ('id', 'KL/15/097/315664'), ('\u0d2a\u0d47\u0d30\u0d4d', '\u0d2e\u0d3f\u0d28\u0d3f'), ('\u0d35\u0d40\u0d1f\u0d4d\u0d1f\u0d41\u0d28\u0d2e\u0d4d\u0d2a\u0d30\u0d4d', '8/187 (14/179)')])
2022-11-09 09:54:26,183 Processing page 19
2022-11-09 09:55:04,003 Processing page 20
2022-11-09 09:55:42,307 Processing page 21
2022-11-09 09:56:19,864 Processing page 22
--- Logging error ---
Traceback (most recent call last):
  File "/home/t-9adar/.conda/envs/env38/lib/python3.8/logging/__init__.py", line 1084, in emit
    stream.write(msg + self.terminator)
UnicodeEncodeError: 'latin-1' codec can't encode characters in position 119-122: ordinal not in range(256)
Call stack:
  File "/home/t-9adar/.conda/envs/env38/lib/python3.8/threading.py", line 890, in _bootstrap
    self._bootstrap_inner()
  File "/home/t-9adar/.conda/envs/env38/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/home/t-9adar/.conda/envs/env38/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/t-9adar/.conda/envs/env38/lib/python3.8/concurrent/futures/thread.py", line 80, in _worker
    work_item.run()
  File "/home/t-9adar/.conda/envs/env38/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "../parse_unsearchable_rolls/parser/parser.py", line 320, in get_data
    processed_box = self.process_boxes_text(text)
  File "../parse_unsearchable_rolls/parser/parser.py", line 149, in process_boxes_text
    result, last_key, is_splitted = self.columns_split(r, self.columns, result, last_key)
  File "../parse_unsearchable_rolls/parser/parser.py", line 255, in columns_split
    result, last_key, is_splitted = self.handle_separator_without_column(r, result, last_key)
  File "../parse_unsearchable_rolls/parser/parser.py", line 226, in handle_separator_without_column
    logging.warning(f'Split uncaught {r} {result}')
Message: "Split uncaught ANgys0.16 PrOk>BO2GJHO3 OrderedDict([('number', '578'), ('id', 'RXD0269837'), ('\u0d2a\u0d47\u0d30\u0d4d', '\u0d35\u0d3f\u0d28\u0d40\u0d24'), ('\u0d35\u0d40\u0d1f\u0d4d\u0d1f\u0d41\u0d28\u0d2e\u0d4d\u0d2a\u0d30\u0d4d', '3/225 (140168)')])"
Arguments: ()
2022-11-09 09:56:47,426 Split uncaught ANgys0.16 PrOk>BO2GJHO3 OrderedDict([('number', '578'), ('id', 'RXD0269837'), ('\u0d2a\u0d47\u0d30\u0d4d', '\u0d35\u0d3f\u0d28\u0d40\u0d24'), ('\u0d35\u0d40\u0d1f\u0d4d\u0d1f\u0d41\u0d28\u0d2e\u0d4d\u0d2a\u0d30\u0d4d', '3/225 (140168)')])
2022-11-09 09:56:57,471 Processing page 23
2022-11-09 09:57:34,612 Processing page 24
2022-11-09 09:58:11,584 Processing page 25
2022-11-09 09:58:49,190 Processing page 26

#################
Epilogue Job Info:
Job ID: 467116[200].acropolis
User ID: t-9adar
Job Name: Kerala2015JobArray-200
Resource List: nodes=1:ppn=1,mem=3400mb,neednodes=1:ppn=1
Resources Used: cput=00:15:07,vmem=2263300kb,walltime=00:15:25,mem=1297296kb,energy_used=0
Exit Code: 271
#################

