2022-11-09 09:44:22,433 Converting data/part240/in/kerala/2015/2015_121_044.pdf to img...
2022-11-09 09:44:30,635 Parsing first and last page data..
2022-11-09 09:44:33,746 Detecting and parsing data/part240/in/kerala/2015/2015_121_044.pdf boxes..
2022-11-09 09:44:33,746 Processing page 3
2022-11-09 09:45:11,124 Processing page 4
2022-11-09 09:45:49,068 Processing page 5
2022-11-09 09:46:26,015 Processing page 6
2022-11-09 09:47:04,870 Processing page 7
2022-11-09 09:47:45,094 Processing page 8
2022-11-09 09:48:21,911 Processing page 9
2022-11-09 09:49:00,530 Processing page 10
2022-11-09 09:49:41,457 Processing page 11
2022-11-09 09:50:21,019 Processing page 12
2022-11-09 09:51:00,424 Processing page 13
2022-11-09 09:51:38,063 Processing page 14
2022-11-09 09:52:14,846 Processing page 15
--- Logging error ---
Traceback (most recent call last):
  File "/home/t-9adar/.conda/envs/env38/lib/python3.8/logging/__init__.py", line 1084, in emit
    stream.write(msg + self.terminator)
UnicodeEncodeError: 'latin-1' codec can't encode characters in position 64-68: ordinal not in range(256)
Call stack:
  File "/home/t-9adar/.conda/envs/env38/lib/python3.8/threading.py", line 890, in _bootstrap
    self._bootstrap_inner()
  File "/home/t-9adar/.conda/envs/env38/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/home/t-9adar/.conda/envs/env38/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/t-9adar/.conda/envs/env38/lib/python3.8/concurrent/futures/thread.py", line 80, in _worker
    work_item.run()
  File "/home/t-9adar/.conda/envs/env38/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "../parse_unsearchable_rolls/parser/parser.py", line 320, in get_data
    processed_box = self.process_boxes_text(text)
  File "../parse_unsearchable_rolls/parser/parser.py", line 149, in process_boxes_text
    result, last_key, is_splitted = self.columns_split(r, self.columns, result, last_key)
  File "../parse_unsearchable_rolls/parser/parser.py", line 255, in columns_split
    result, last_key, is_splitted = self.handle_separator_without_column(r, result, last_key)
  File "../parse_unsearchable_rolls/parser/parser.py", line 226, in handle_separator_without_column
    logging.warning(f'Split uncaught {r} {result}')
Message: "Split uncaught sdomralod cue ©2U)2&> 94 \u0d2a\u0d3f\u0d33\u0d4d\u0d33 OrderedDict([('number', '\u0d26\u0d41'), ('id', 'KL/16/108/234120'), ('\u0d2a\u0d47\u0d30\u0d4d', '\u0d05\u0d2e\u0d4d\u0d2a\u0d3f\u0d33\u0d3f')])"
Arguments: ()
2022-11-09 09:52:53,335 Split uncaught sdomralod cue ©2U)2&> 94 \u0d2a\u0d3f\u0d33\u0d4d\u0d33 OrderedDict([('number', '\u0d26\u0d41'), ('id', 'KL/16/108/234120'), ('\u0d2a\u0d47\u0d30\u0d4d', '\u0d05\u0d2e\u0d4d\u0d2a\u0d3f\u0d33\u0d3f')])
2022-11-09 09:52:53,428 Processing page 16
2022-11-09 09:53:31,748 Processing page 17
2022-11-09 09:54:09,906 Processing page 18
2022-11-09 09:54:49,159 Processing page 19
2022-11-09 09:55:26,688 Processing page 20
2022-11-09 09:56:05,196 Processing page 21
2022-11-09 09:56:43,306 Processing page 22
2022-11-09 09:57:21,007 Processing page 23
2022-11-09 09:57:58,543 Processing page 24
2022-11-09 09:58:37,218 Processing page 25
--- Logging error ---
Traceback (most recent call last):
  File "/home/t-9adar/.conda/envs/env38/lib/python3.8/logging/__init__.py", line 1084, in emit
    stream.write(msg + self.terminator)
UnicodeEncodeError: 'latin-1' codec can't encode characters in position 39-43: ordinal not in range(256)
Call stack:
  File "/home/t-9adar/.conda/envs/env38/lib/python3.8/threading.py", line 890, in _bootstrap
    self._bootstrap_inner()
  File "/home/t-9adar/.conda/envs/env38/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/home/t-9adar/.conda/envs/env38/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/t-9adar/.conda/envs/env38/lib/python3.8/concurrent/futures/thread.py", line 80, in _worker
    work_item.run()
  File "/home/t-9adar/.conda/envs/env38/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "../parse_unsearchable_rolls/parser/parser.py", line 320, in get_data
    processed_box = self.process_boxes_text(text)
  File "../parse_unsearchable_rolls/parser/parser.py", line 149, in process_boxes_text
    result, last_key, is_splitted = self.columns_split(r, self.columns, result, last_key)
  File "../parse_unsearchable_rolls/parser/parser.py", line 255, in columns_split
    result, last_key, is_splitted = self.handle_separator_without_column(r, result, last_key)
  File "../parse_unsearchable_rolls/parser/parser.py", line 226, in handle_separator_without_column
    logging.warning(f'Split uncaught {r} {result}')
Message: "Split uncaught \u0d2a\u0d47\u0d30\u0d4d\u200c =) OrderedDict([('number', '677'), ('id', 'BNJ1441740')])"
Arguments: ()
2022-11-09 09:58:55,073 Split uncaught \u0d2a\u0d47\u0d30\u0d4d\u200c =) OrderedDict([('number', '677'), ('id', 'BNJ1441740')])
2022-11-09 09:59:16,196 Processing page 26

#################
Epilogue Job Info:
Job ID: 467116[240].acropolis
User ID: t-9adar
Job Name: Kerala2015JobArray-240
Resource List: nodes=1:ppn=1,mem=3400mb,neednodes=1:ppn=1
Resources Used: cput=00:15:01,vmem=2267968kb,walltime=00:15:28,mem=1304228kb,energy_used=0
Exit Code: 271
#################

