2022-11-09 09:44:10,434 Converting data/part176/in/kerala/2015/2015_091_129.pdf to img...
2022-11-09 09:44:17,989 Parsing first and last page data..
2022-11-09 09:44:20,307 Detecting and parsing data/part176/in/kerala/2015/2015_091_129.pdf boxes..
2022-11-09 09:44:20,307 Processing page 3
2022-11-09 09:44:44,183 Processing page 4
2022-11-09 09:45:11,314 Processing page 5
2022-11-09 09:45:35,936 Processing page 6
2022-11-09 09:46:01,198 Processing page 7
2022-11-09 09:46:25,971 Processing page 8
2022-11-09 09:46:50,707 Processing page 9
2022-11-09 09:47:13,914 Processing page 10
2022-11-09 09:47:39,079 Processing page 11
2022-11-09 09:48:06,522 Processing page 12
2022-11-09 09:48:31,027 Processing page 13
2022-11-09 09:48:54,784 Processing page 14
2022-11-09 09:49:19,746 Processing page 15
2022-11-09 09:49:45,504 Processing page 16
2022-11-09 09:50:09,879 Processing page 17
2022-11-09 09:50:33,873 Processing page 18
2022-11-09 09:51:05,459 Processing page 19
2022-11-09 09:51:31,360 Processing page 20
2022-11-09 09:51:55,028 Processing page 21
2022-11-09 09:52:19,796 Processing page 22
2022-11-09 09:52:43,764 Processing page 23
2022-11-09 09:53:07,318 Processing page 24
2022-11-09 09:53:30,906 Processing page 25
2022-11-09 09:53:54,328 Processing page 26
2022-11-09 09:54:17,583 Processing page 27
2022-11-09 09:54:41,489 Processing page 28
2022-11-09 09:55:05,583 Processing page 29
2022-11-09 09:55:29,300 Processing page 30
2022-11-09 09:55:53,243 Processing page 31
2022-11-09 09:56:16,712 Processing page 32
2022-11-09 09:56:41,681 Processing page 33
2022-11-09 09:57:06,475 Processing page 34
2022-11-09 09:57:32,591 Processing page 35
--- Logging error ---
Traceback (most recent call last):
  File "/home/t-9adar/.conda/envs/env38/lib/python3.8/logging/__init__.py", line 1084, in emit
    stream.write(msg + self.terminator)
UnicodeEncodeError: 'latin-1' codec can't encode characters in position 39-46: ordinal not in range(256)
Call stack:
  File "/home/t-9adar/.conda/envs/env38/lib/python3.8/threading.py", line 890, in _bootstrap
    self._bootstrap_inner()
  File "/home/t-9adar/.conda/envs/env38/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/home/t-9adar/.conda/envs/env38/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/t-9adar/.conda/envs/env38/lib/python3.8/concurrent/futures/thread.py", line 80, in _worker
    work_item.run()
  File "/home/t-9adar/.conda/envs/env38/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "../parse_unsearchable_rolls/parser/parser.py", line 320, in get_data
    processed_box = self.process_boxes_text(text)
  File "../parse_unsearchable_rolls/parser/parser.py", line 149, in process_boxes_text
    result, last_key, is_splitted = self.columns_split(r, self.columns, result, last_key)
  File "../parse_unsearchable_rolls/parser/parser.py", line 255, in columns_split
    result, last_key, is_splitted = self.handle_separator_without_column(r, result, last_key)
  File "../parse_unsearchable_rolls/parser/parser.py", line 226, in handle_separator_without_column
    logging.warning(f'Split uncaught {r} {result}')
Message: "Split uncaught \u0d05\u0d1a\u0d4d\u0d1b\u0d28\u0d4d\u0d31\u0d46 cold Od> Od CNIADAIC OrderedDict([('number', '980'), ('id', 'NJG0290122'), ('\u0d2a\u0d47\u0d30\u0d4d', 'molar ad el')])"
Arguments: ()
2022-11-09 09:57:44,615 Split uncaught \u0d05\u0d1a\u0d4d\u0d1b\u0d28\u0d4d\u0d31\u0d46 cold Od> Od CNIADAIC OrderedDict([('number', '980'), ('id', 'NJG0290122'), ('\u0d2a\u0d47\u0d30\u0d4d', 'molar ad el')])
2022-11-09 09:58:01,097 Processing page 36
2022-11-09 09:58:26,895 Processing page 37
2022-11-09 09:58:58,087 Processing page 38

#################
Epilogue Job Info:
Job ID: 467116[176].acropolis
User ID: t-9adar
Job Name: Kerala2015JobArray-176
Resource List: nodes=1:ppn=1,mem=3400mb,neednodes=1:ppn=1
Resources Used: cput=00:15:04,vmem=2682000kb,walltime=00:15:25,mem=1721968kb,energy_used=0
Exit Code: 271
#################

