2022-11-09 09:44:16,685 Converting data/part129/in/kerala/2015/2015_067_143.pdf to img...
2022-11-09 09:44:22,297 Parsing first and last page data..
2022-11-09 09:44:25,298 Detecting and parsing data/part129/in/kerala/2015/2015_067_143.pdf boxes..
2022-11-09 09:44:25,298 Processing page 3
2022-11-09 09:44:49,115 Processing page 4
2022-11-09 09:45:13,315 Processing page 5
2022-11-09 09:45:36,923 Processing page 6
2022-11-09 09:46:00,566 Processing page 7
2022-11-09 09:46:24,585 Processing page 8
2022-11-09 09:46:48,336 Processing page 9
2022-11-09 09:47:12,294 Processing page 10
2022-11-09 09:47:36,312 Processing page 11
2022-11-09 09:48:00,130 Processing page 12
2022-11-09 09:48:24,237 Processing page 13
2022-11-09 09:48:47,815 Processing page 14
2022-11-09 09:49:12,230 Processing page 15
2022-11-09 09:49:34,922 Processing page 16
2022-11-09 09:49:58,249 Processing page 17
2022-11-09 09:50:21,890 Processing page 18
2022-11-09 09:50:45,910 Processing page 19
2022-11-09 09:51:09,727 Processing page 20
2022-11-09 09:51:33,941 Processing page 21
2022-11-09 09:51:58,181 Processing page 22
2022-11-09 09:52:21,776 Processing page 23
2022-11-09 09:52:45,571 Processing page 24
2022-11-09 09:53:09,554 Processing page 25
2022-11-09 09:53:33,098 Processing page 26
2022-11-09 09:53:57,839 Processing page 27
2022-11-09 09:54:21,590 Processing page 28
2022-11-09 09:54:45,583 Processing page 29
2022-11-09 09:55:09,899 Processing page 30
--- Logging error ---
Traceback (most recent call last):
  File "/home/t-9adar/.conda/envs/env38/lib/python3.8/logging/__init__.py", line 1084, in emit
    stream.write(msg + self.terminator)
UnicodeEncodeError: 'latin-1' codec can't encode characters in position 118-121: ordinal not in range(256)
Call stack:
  File "/home/t-9adar/.conda/envs/env38/lib/python3.8/threading.py", line 890, in _bootstrap
    self._bootstrap_inner()
  File "/home/t-9adar/.conda/envs/env38/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/home/t-9adar/.conda/envs/env38/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/t-9adar/.conda/envs/env38/lib/python3.8/concurrent/futures/thread.py", line 80, in _worker
    work_item.run()
  File "/home/t-9adar/.conda/envs/env38/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "../parse_unsearchable_rolls/parser/parser.py", line 320, in get_data
    processed_box = self.process_boxes_text(text)
  File "../parse_unsearchable_rolls/parser/parser.py", line 149, in process_boxes_text
    result, last_key, is_splitted = self.columns_split(r, self.columns, result, last_key)
  File "../parse_unsearchable_rolls/parser/parser.py", line 255, in columns_split
    result, last_key, is_splitted = self.handle_separator_without_column(r, result, last_key)
  File "../parse_unsearchable_rolls/parser/parser.py", line 226, in handle_separator_without_column
    logging.warning(f'Split uncaught {r} {result}')
Message: "Split uncaught sdomalog ete (Gle>JaIB OrderedDict([('number', '840'), ('id', 'GJX1204007'), ('\u0d2a\u0d47\u0d30\u0d4d', 'mail')])"
Arguments: ()
2022-11-09 09:55:11,910 Split uncaught sdomalog ete (Gle>JaIB OrderedDict([('number', '840'), ('id', 'GJX1204007'), ('\u0d2a\u0d47\u0d30\u0d4d', 'mail')])
2022-11-09 09:55:33,680 Processing page 31
2022-11-09 09:55:57,076 Processing page 32
2022-11-09 09:56:20,917 Processing page 33
2022-11-09 09:56:45,775 Processing page 34
2022-11-09 09:57:10,286 Processing page 35
2022-11-09 09:57:35,213 Processing page 36
2022-11-09 09:57:59,727 Processing page 37
2022-11-09 09:58:25,037 Processing page 38
2022-11-09 09:58:50,144 Processing page 39

#################
Epilogue Job Info:
Job ID: 467116[129].acropolis
User ID: t-9adar
Job Name: Kerala2015JobArray-129
Resource List: nodes=1:ppn=1,mem=3400mb,neednodes=1:ppn=1
Resources Used: cput=00:14:48,vmem=2774540kb,walltime=00:15:22,mem=1811096kb,energy_used=0
Exit Code: 271
#################

