2022-11-09 09:44:17,655 Converting data/part276/in/kerala/2015/2015_138_073.pdf to img...
2022-11-09 09:44:24,543 Parsing first and last page data..
2022-11-09 09:44:26,384 Detecting and parsing data/part276/in/kerala/2015/2015_138_073.pdf boxes..
2022-11-09 09:44:26,384 Processing page 3
2022-11-09 09:44:50,216 Processing page 4
2022-11-09 09:45:13,789 Processing page 5
2022-11-09 09:45:37,388 Processing page 6
2022-11-09 09:46:01,200 Processing page 7
2022-11-09 09:46:24,486 Processing page 8
2022-11-09 09:46:47,270 Processing page 9
2022-11-09 09:47:10,238 Processing page 10
2022-11-09 09:47:32,838 Processing page 11
2022-11-09 09:47:55,781 Processing page 12
2022-11-09 09:48:18,577 Processing page 13
2022-11-09 09:48:42,641 Processing page 14
2022-11-09 09:49:05,618 Processing page 15
2022-11-09 09:49:29,383 Processing page 16
2022-11-09 09:49:53,035 Processing page 17
2022-11-09 09:50:16,305 Processing page 18
2022-11-09 09:50:39,830 Processing page 19
2022-11-09 09:51:04,115 Processing page 20
2022-11-09 09:51:27,089 Processing page 21
2022-11-09 09:51:50,525 Processing page 22
2022-11-09 09:52:13,256 Processing page 23
2022-11-09 09:52:36,465 Processing page 24
2022-11-09 09:52:59,731 Processing page 25
2022-11-09 09:53:23,072 Processing page 26
2022-11-09 09:53:46,286 Processing page 27
2022-11-09 09:54:08,846 Processing page 28
2022-11-09 09:54:32,207 Processing page 29
2022-11-09 09:54:56,712 Processing page 30
--- Logging error ---
Traceback (most recent call last):
  File "/home/t-9adar/.conda/envs/env38/lib/python3.8/logging/__init__.py", line 1084, in emit
    stream.write(msg + self.terminator)
UnicodeEncodeError: 'latin-1' codec can't encode characters in position 123-126: ordinal not in range(256)
Call stack:
  File "/home/t-9adar/.conda/envs/env38/lib/python3.8/threading.py", line 890, in _bootstrap
    self._bootstrap_inner()
  File "/home/t-9adar/.conda/envs/env38/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/home/t-9adar/.conda/envs/env38/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/t-9adar/.conda/envs/env38/lib/python3.8/concurrent/futures/thread.py", line 80, in _worker
    work_item.run()
  File "/home/t-9adar/.conda/envs/env38/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "../parse_unsearchable_rolls/parser/parser.py", line 320, in get_data
    processed_box = self.process_boxes_text(text)
  File "../parse_unsearchable_rolls/parser/parser.py", line 149, in process_boxes_text
    result, last_key, is_splitted = self.columns_split(r, self.columns, result, last_key)
  File "../parse_unsearchable_rolls/parser/parser.py", line 255, in columns_split
    result, last_key, is_splitted = self.handle_separator_without_column(r, result, last_key)
  File "../parse_unsearchable_rolls/parser/parser.py", line 226, in handle_separator_without_column
    logging.warning(f'Split uncaught {r} {result}')
Message: "Split uncaught sdomalag ete CBlk>JAIVR MIS OrderedDict([('number', '813'), ('id', 'HFJ1354372'), ('\u0d2a\u0d47\u0d30\u0d4d', 'eamilsl card')])"
Arguments: ()
2022-11-09 09:55:18,009 Split uncaught sdomalag ete CBlk>JAIVR MIS OrderedDict([('number', '813'), ('id', 'HFJ1354372'), ('\u0d2a\u0d47\u0d30\u0d4d', 'eamilsl card')])
2022-11-09 09:55:19,961 Processing page 31
2022-11-09 09:55:43,842 Processing page 32
2022-11-09 09:56:07,584 Processing page 33
2022-11-09 09:56:31,201 Processing page 34
2022-11-09 09:56:54,681 Processing page 35
2022-11-09 09:57:17,201 Processing page 36
2022-11-09 09:57:41,543 Processing page 37
2022-11-09 09:58:05,362 Processing page 38
2022-11-09 09:58:29,061 Processing page 39
2022-11-09 09:58:52,931 Processing page 40
2022-11-09 09:59:16,572 Processing page 41

#################
Epilogue Job Info:
Job ID: 467116[276].acropolis
User ID: t-9adar
Job Name: Kerala2015JobArray-276
Resource List: nodes=1:ppn=1,mem=3400mb,neednodes=1:ppn=1
Resources Used: cput=00:15:15,vmem=2778292kb,walltime=00:15:21,mem=1816328kb,energy_used=0
Exit Code: 271
#################

