2022-11-09 09:43:57,662 Converting data/part19/in/kerala/2015/2015_009_127.pdf to img...
2022-11-09 09:44:03,684 Parsing first and last page data..
2022-11-09 09:44:06,760 Detecting and parsing data/part19/in/kerala/2015/2015_009_127.pdf boxes..
2022-11-09 09:44:06,760 Processing page 3
2022-11-09 09:44:36,841 Processing page 4
2022-11-09 09:45:06,166 Processing page 5
2022-11-09 09:45:36,925 Processing page 6
2022-11-09 09:46:08,402 Processing page 7
2022-11-09 09:46:35,968 Processing page 8
2022-11-09 09:47:07,972 Processing page 9
2022-11-09 09:47:37,979 Processing page 10
2022-11-09 09:48:07,211 Processing page 11
2022-11-09 09:48:39,584 Processing page 12
2022-11-09 09:49:08,363 Processing page 13
2022-11-09 09:49:40,467 Processing page 14
2022-11-09 09:50:08,139 Processing page 15
2022-11-09 09:50:39,180 Processing page 16
2022-11-09 09:51:06,409 Processing page 17
2022-11-09 09:51:37,065 Processing page 18
2022-11-09 09:52:05,176 Processing page 19
2022-11-09 09:52:34,591 Processing page 20
2022-11-09 09:53:06,010 Processing page 21
2022-11-09 09:53:36,064 Processing page 22
2022-11-09 09:54:07,118 Processing page 23
2022-11-09 09:54:38,174 Processing page 24
2022-11-09 09:55:05,476 Processing page 25
2022-11-09 09:55:35,562 Processing page 26
2022-11-09 09:56:02,028 Processing page 27
--- Logging error ---
Traceback (most recent call last):
  File "/home/t-9adar/.conda/envs/env38/lib/python3.8/logging/__init__.py", line 1084, in emit
    stream.write(msg + self.terminator)
UnicodeEncodeError: 'latin-1' codec can't encode characters in position 39-40: ordinal not in range(256)
Call stack:
  File "/home/t-9adar/.conda/envs/env38/lib/python3.8/threading.py", line 890, in _bootstrap
    self._bootstrap_inner()
  File "/home/t-9adar/.conda/envs/env38/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/home/t-9adar/.conda/envs/env38/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/t-9adar/.conda/envs/env38/lib/python3.8/concurrent/futures/thread.py", line 80, in _worker
    work_item.run()
  File "/home/t-9adar/.conda/envs/env38/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "../parse_unsearchable_rolls/parser/parser.py", line 320, in get_data
    processed_box = self.process_boxes_text(text)
  File "../parse_unsearchable_rolls/parser/parser.py", line 149, in process_boxes_text
    result, last_key, is_splitted = self.columns_split(r, self.columns, result, last_key)
  File "../parse_unsearchable_rolls/parser/parser.py", line 255, in columns_split
    result, last_key, is_splitted = self.handle_separator_without_column(r, result, last_key)
  File "../parse_unsearchable_rolls/parser/parser.py", line 226, in handle_separator_without_column
    logging.warning(f'Split uncaught {r} {result}')
Message: "Split uncaught \u0d2a\u0d3f 2Dee0> OrderedDict([('number', '726'), ('id', 'KL/02/006/270259'), ('\u0d2a\u0d47\u0d30\u0d4d', '\u0d0f\u0d32\u0d3f\u0d15\u0d4d\u0d15\u0d41\u0d1f\u0d4d\u0d1f\u0d3f')])"
Arguments: ()
2022-11-09 09:56:25,261 Split uncaught \u0d2a\u0d3f 2Dee0> OrderedDict([('number', '726'), ('id', 'KL/02/006/270259'), ('\u0d2a\u0d47\u0d30\u0d4d', '\u0d0f\u0d32\u0d3f\u0d15\u0d4d\u0d15\u0d41\u0d1f\u0d4d\u0d1f\u0d3f')])
2022-11-09 09:56:29,674 Processing page 28
2022-11-09 09:56:57,892 Processing page 29
2022-11-09 09:57:27,630 Processing page 30
2022-11-09 09:57:59,705 Processing page 31
2022-11-09 09:58:27,560 Processing page 32

#################
Epilogue Job Info:
Job ID: 467116[19].acropolis
User ID: t-9adar
Job Name: Kerala2015JobArray-19
Resource List: nodes=1:ppn=1,mem=3400mb,neednodes=1:ppn=1
Resources Used: cput=00:14:52,vmem=2493456kb,walltime=00:15:12,mem=1527948kb,energy_used=0
Exit Code: 271
#################

