2022-11-09 09:44:09,589 Converting data/part165/in/kerala/2015/2015_086_063.pdf to img...
2022-11-09 09:44:18,246 Parsing first and last page data..
2022-11-09 09:44:21,275 Detecting and parsing data/part165/in/kerala/2015/2015_086_063.pdf boxes..
2022-11-09 09:44:21,275 Processing page 3
--- Logging error ---
Traceback (most recent call last):
  File "/home/t-9adar/.conda/envs/env38/lib/python3.8/logging/__init__.py", line 1084, in emit
    stream.write(msg + self.terminator)
UnicodeEncodeError: 'latin-1' codec can't encode characters in position 122-125: ordinal not in range(256)
Call stack:
  File "/home/t-9adar/.conda/envs/env38/lib/python3.8/threading.py", line 890, in _bootstrap
    self._bootstrap_inner()
  File "/home/t-9adar/.conda/envs/env38/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/home/t-9adar/.conda/envs/env38/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/t-9adar/.conda/envs/env38/lib/python3.8/concurrent/futures/thread.py", line 80, in _worker
    work_item.run()
  File "/home/t-9adar/.conda/envs/env38/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "../parse_unsearchable_rolls/parser/parser.py", line 320, in get_data
    processed_box = self.process_boxes_text(text)
  File "../parse_unsearchable_rolls/parser/parser.py", line 149, in process_boxes_text
    result, last_key, is_splitted = self.columns_split(r, self.columns, result, last_key)
  File "../parse_unsearchable_rolls/parser/parser.py", line 255, in columns_split
    result, last_key, is_splitted = self.handle_separator_without_column(r, result, last_key)
  File "../parse_unsearchable_rolls/parser/parser.py", line 226, in handle_separator_without_column
    logging.warning(f'Split uncaught {r} {result}')
Message: "Split uncaught Algyenic OGn0.3,36>}S1 OrderedDict([('number', '5'), ('id', 'KL/12/081/438272'), ('\u0d2a\u0d47\u0d30\u0d4d', '\u0d38\u0d30\u0d38\u0d41'), ('\u0d35\u0d40\u0d1f\u0d4d\u0d1f\u0d41\u0d28\u0d2e\u0d4d\u0d2a\u0d30\u0d4d', '6/251 (41316)')])"
Arguments: ()
2022-11-09 09:44:28,744 Split uncaught Algyenic OGn0.3,36>}S1 OrderedDict([('number', '5'), ('id', 'KL/12/081/438272'), ('\u0d2a\u0d47\u0d30\u0d4d', '\u0d38\u0d30\u0d38\u0d41'), ('\u0d35\u0d40\u0d1f\u0d4d\u0d1f\u0d41\u0d28\u0d2e\u0d4d\u0d2a\u0d30\u0d4d', '6/251 (41316)')])
--- Logging error ---
Traceback (most recent call last):
  File "/home/t-9adar/.conda/envs/env38/lib/python3.8/logging/__init__.py", line 1084, in emit
    stream.write(msg + self.terminator)
UnicodeEncodeError: 'latin-1' codec can't encode characters in position 39-40: ordinal not in range(256)
Call stack:
  File "/home/t-9adar/.conda/envs/env38/lib/python3.8/threading.py", line 890, in _bootstrap
    self._bootstrap_inner()
  File "/home/t-9adar/.conda/envs/env38/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/home/t-9adar/.conda/envs/env38/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/t-9adar/.conda/envs/env38/lib/python3.8/concurrent/futures/thread.py", line 80, in _worker
    work_item.run()
  File "/home/t-9adar/.conda/envs/env38/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "../parse_unsearchable_rolls/parser/parser.py", line 320, in get_data
    processed_box = self.process_boxes_text(text)
  File "../parse_unsearchable_rolls/parser/parser.py", line 149, in process_boxes_text
    result, last_key, is_splitted = self.columns_split(r, self.columns, result, last_key)
  File "../parse_unsearchable_rolls/parser/parser.py", line 255, in columns_split
    result, last_key, is_splitted = self.handle_separator_without_column(r, result, last_key)
  File "../parse_unsearchable_rolls/parser/parser.py", line 226, in handle_separator_without_column
    logging.warning(f'Split uncaught {r} {result}')
Message: "Split uncaught \u0d28\u0d3f Or0.3,36>}S) OrderedDict([('number', '24'), ('id', 'KL/12/081/438651'), ('\u0d2a\u0d47\u0d30\u0d4d', '\u0d15\u0d41\u0d1e\u0d4d\u0d1e\u0d4d\\u200c'), ('\u0d05\u0d1a\u0d4d\u0d1b\u0d28\u0d4d\u0d31\u0d46 \u0d2a\u0d47\u0d30\u0d4d', '\u0d36\u0d19\u0d4d\u0d15\u0d41'), ('\u0d35\u0d40\u0d1f\u0d4d\u0d1f\u0d41\u0d28\u0d2e\u0d4d\u0d2a\u0d30\u0d4d', '6/251 (4/316)')])"
Arguments: ()
2022-11-09 09:44:30,216 Split uncaught \u0d28\u0d3f Or0.3,36>}S) OrderedDict([('number', '24'), ('id', 'KL/12/081/438651'), ('\u0d2a\u0d47\u0d30\u0d4d', '\u0d15\u0d41\u0d1e\u0d4d\u0d1e\u0d4d\u200c'), ('\u0d05\u0d1a\u0d4d\u0d1b\u0d28\u0d4d\u0d31\u0d46 \u0d2a\u0d47\u0d30\u0d4d', '\u0d36\u0d19\u0d4d\u0d15\u0d41'), ('\u0d35\u0d40\u0d1f\u0d4d\u0d1f\u0d41\u0d28\u0d2e\u0d4d\u0d2a\u0d30\u0d4d', '6/251 (4/316)')])
2022-11-09 09:44:56,403 Processing page 4
--- Logging error ---
Traceback (most recent call last):
  File "/home/t-9adar/.conda/envs/env38/lib/python3.8/logging/__init__.py", line 1084, in emit
    stream.write(msg + self.terminator)
UnicodeEncodeError: 'latin-1' codec can't encode characters in position 39-40: ordinal not in range(256)
Call stack:
  File "/home/t-9adar/.conda/envs/env38/lib/python3.8/threading.py", line 890, in _bootstrap
    self._bootstrap_inner()
  File "/home/t-9adar/.conda/envs/env38/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/home/t-9adar/.conda/envs/env38/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/t-9adar/.conda/envs/env38/lib/python3.8/concurrent/futures/thread.py", line 80, in _worker
    work_item.run()
  File "/home/t-9adar/.conda/envs/env38/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "../parse_unsearchable_rolls/parser/parser.py", line 320, in get_data
    processed_box = self.process_boxes_text(text)
  File "../parse_unsearchable_rolls/parser/parser.py", line 149, in process_boxes_text
    result, last_key, is_splitted = self.columns_split(r, self.columns, result, last_key)
  File "../parse_unsearchable_rolls/parser/parser.py", line 255, in columns_split
    result, last_key, is_splitted = self.handle_separator_without_column(r, result, last_key)
  File "../parse_unsearchable_rolls/parser/parser.py", line 226, in handle_separator_without_column
    logging.warning(f'Split uncaught {r} {result}')
Message: "Split uncaught \u0d35\u0d3f OdhI.2,3>)S1 OrderedDict([('number', '32'), ('id', 'KL/12/081/438389'), ('\u0d2a\u0d47\u0d30\u0d4d', '\u0d1f\u0d4d\u0d1f\u0d3f]'), ('\u0d35\u0d40\u0d1f\u0d4d\u0d1f\u0d41\u0d28\u0d2e\u0d4d\u0d2a\u0d30\u0d4d', '6/252 (15)')])"
Arguments: ()
2022-11-09 09:45:30,393 Split uncaught \u0d35\u0d3f OdhI.2,3>)S1 OrderedDict([('number', '32'), ('id', 'KL/12/081/438389'), ('\u0d2a\u0d47\u0d30\u0d4d', '\u0d1f\u0d4d\u0d1f\u0d3f]'), ('\u0d35\u0d40\u0d1f\u0d4d\u0d1f\u0d41\u0d28\u0d2e\u0d4d\u0d2a\u0d30\u0d4d', '6/252 (15)')])
2022-11-09 09:45:32,360 Processing page 5
2022-11-09 09:46:08,743 Processing page 6
2022-11-09 09:46:44,809 Processing page 7
2022-11-09 09:47:20,801 Processing page 8
2022-11-09 09:47:57,827 Processing page 9
2022-11-09 09:48:34,495 Processing page 10
2022-11-09 09:49:11,195 Processing page 11
2022-11-09 09:49:47,322 Processing page 12
2022-11-09 09:50:24,055 Processing page 13
2022-11-09 09:50:47,579 Processing page 14
2022-11-09 09:51:23,772 Processing page 15
2022-11-09 09:51:59,726 Processing page 16
2022-11-09 09:52:36,380 Processing page 17
2022-11-09 09:53:11,949 Processing page 18
2022-11-09 09:53:46,856 Processing page 19
2022-11-09 09:54:22,959 Processing page 20
2022-11-09 09:54:59,165 Processing page 21
2022-11-09 09:55:35,399 Processing page 22
2022-11-09 09:56:11,486 Processing page 23
2022-11-09 09:56:47,807 Processing page 24
2022-11-09 09:57:23,775 Processing page 25
2022-11-09 09:58:00,439 Processing page 26
2022-11-09 09:58:37,379 Processing page 27
2022-11-09 09:59:13,246 Processing page 28

#################
Epilogue Job Info:
Job ID: 467116[165].acropolis
User ID: t-9adar
Job Name: Kerala2015JobArray-165
Resource List: nodes=1:ppn=1,mem=3400mb,neednodes=1:ppn=1
Resources Used: cput=00:15:05,vmem=2340600kb,walltime=00:15:24,mem=1375584kb,energy_used=0
Exit Code: 271
#################

