2022-11-09 09:44:23,665 Converting data/part241/in/kerala/2015/2015_121_120.pdf to img...
2022-11-09 09:44:30,604 Parsing first and last page data..
2022-11-09 09:44:33,848 Detecting and parsing data/part241/in/kerala/2015/2015_121_120.pdf boxes..
2022-11-09 09:44:33,848 Processing page 3
2022-11-09 09:45:10,154 Processing page 4
2022-11-09 09:45:45,035 Processing page 5
2022-11-09 09:46:21,698 Processing page 6
2022-11-09 09:46:58,297 Processing page 7
2022-11-09 09:47:34,021 Processing page 8
2022-11-09 09:48:11,059 Processing page 9
2022-11-09 09:48:46,581 Processing page 10
2022-11-09 09:49:22,995 Processing page 11
2022-11-09 09:49:58,281 Processing page 12
2022-11-09 09:50:34,184 Processing page 13
2022-11-09 09:51:09,886 Processing page 14
2022-11-09 09:51:45,507 Processing page 15
2022-11-09 09:52:22,237 Processing page 16
2022-11-09 09:52:59,771 Processing page 17
2022-11-09 09:53:35,699 Processing page 18
2022-11-09 09:54:11,603 Processing page 19
2022-11-09 09:54:48,114 Processing page 20
2022-11-09 09:55:25,290 Processing page 21
2022-11-09 09:56:00,889 Processing page 22
2022-11-09 09:56:35,849 Processing page 23
2022-11-09 09:57:11,439 Processing page 24
2022-11-09 09:57:46,491 Processing page 25
2022-11-09 09:58:23,445 Processing page 26
--- Logging error ---
Traceback (most recent call last):
  File "/home/t-9adar/.conda/envs/env38/lib/python3.8/logging/__init__.py", line 1084, in emit
    stream.write(msg + self.terminator)
UnicodeEncodeError: 'latin-1' codec can't encode characters in position 116-119: ordinal not in range(256)
Call stack:
  File "/home/t-9adar/.conda/envs/env38/lib/python3.8/threading.py", line 890, in _bootstrap
    self._bootstrap_inner()
  File "/home/t-9adar/.conda/envs/env38/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/home/t-9adar/.conda/envs/env38/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/t-9adar/.conda/envs/env38/lib/python3.8/concurrent/futures/thread.py", line 80, in _worker
    work_item.run()
  File "/home/t-9adar/.conda/envs/env38/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "../parse_unsearchable_rolls/parser/parser.py", line 320, in get_data
    processed_box = self.process_boxes_text(text)
  File "../parse_unsearchable_rolls/parser/parser.py", line 149, in process_boxes_text
    result, last_key, is_splitted = self.columns_split(r, self.columns, result, last_key)
  File "../parse_unsearchable_rolls/parser/parser.py", line 255, in columns_split
    result, last_key, is_splitted = self.handle_separator_without_column(r, result, last_key)
  File "../parse_unsearchable_rolls/parser/parser.py", line 226, in handle_separator_without_column
    logging.warning(f'Split uncaught {r} {result}')
Message: "Split uncaught alga 2/222 = (15/131) OrderedDict([('number', '13'), ('id', 'BNJ2487189'), ('\u0d2a\u0d47\u0d30\u0d4d', '\u0d05\u0d28\u0d40\u0d37\u0d4d\\u200c'), ('\u0d05\u0d1a\u0d4d\u0d1b\u0d28\u0d4d\u0d31\u0d46 \u0d2a\u0d47\u0d30\u0d4d', '\u0d38\u0d41\u0d27\u0d3e\u0d15\u0d30\u0d28\u0d4d\\u200d')])"
Arguments: ()
2022-11-09 09:58:33,520 Split uncaught alga 2/222 = (15/131) OrderedDict([('number', '13'), ('id', 'BNJ2487189'), ('\u0d2a\u0d47\u0d30\u0d4d', '\u0d05\u0d28\u0d40\u0d37\u0d4d\u200c'), ('\u0d05\u0d1a\u0d4d\u0d1b\u0d28\u0d4d\u0d31\u0d46 \u0d2a\u0d47\u0d30\u0d4d', '\u0d38\u0d41\u0d27\u0d3e\u0d15\u0d30\u0d28\u0d4d\u200d')])
2022-11-09 09:59:00,869 Processing page 27

#################
Epilogue Job Info:
Job ID: 467116[241].acropolis
User ID: t-9adar
Job Name: Kerala2015JobArray-241
Resource List: nodes=1:ppn=1,mem=3400mb,neednodes=1:ppn=1
Resources Used: cput=00:15:01,vmem=2323108kb,walltime=00:15:29,mem=1359508kb,energy_used=0
Exit Code: 271
#################

