2022-11-09 09:43:57,625 Converting data/part10/in/kerala/2015/2015_005_067.pdf to img...
2022-11-09 09:44:08,929 Parsing first and last page data..
2022-11-09 09:44:12,297 Detecting and parsing data/part10/in/kerala/2015/2015_005_067.pdf boxes..
2022-11-09 09:44:12,297 Processing page 3
2022-11-09 09:44:49,590 Processing page 4
2022-11-09 09:45:22,563 Processing page 5
--- Logging error ---
Traceback (most recent call last):
  File "/home/t-9adar/.conda/envs/env38/lib/python3.8/logging/__init__.py", line 1084, in emit
    stream.write(msg + self.terminator)
UnicodeEncodeError: 'latin-1' codec can't encode characters in position 39-43: ordinal not in range(256)
Call stack:
  File "/home/t-9adar/.conda/envs/env38/lib/python3.8/threading.py", line 890, in _bootstrap
    self._bootstrap_inner()
  File "/home/t-9adar/.conda/envs/env38/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/home/t-9adar/.conda/envs/env38/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/t-9adar/.conda/envs/env38/lib/python3.8/concurrent/futures/thread.py", line 80, in _worker
    work_item.run()
  File "/home/t-9adar/.conda/envs/env38/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "../parse_unsearchable_rolls/parser/parser.py", line 320, in get_data
    processed_box = self.process_boxes_text(text)
  File "../parse_unsearchable_rolls/parser/parser.py", line 149, in process_boxes_text
    result, last_key, is_splitted = self.columns_split(r, self.columns, result, last_key)
  File "../parse_unsearchable_rolls/parser/parser.py", line 255, in columns_split
    result, last_key, is_splitted = self.handle_separator_without_column(r, result, last_key)
  File "../parse_unsearchable_rolls/parser/parser.py", line 226, in handle_separator_without_column
    logging.warning(f'Split uncaught {r} {result}')
Message: "Split uncaught \u0d2a\u0d47\u0d30\u0d4d\u200c =) OrderedDict([('number', '65'), ('id', 'KL/01/005/324757')])"
Arguments: ()
2022-11-09 09:45:52,748 Split uncaught \u0d2a\u0d47\u0d30\u0d4d\u200c =) OrderedDict([('number', '65'), ('id', 'KL/01/005/324757')])
2022-11-09 09:45:57,690 Processing page 6
2022-11-09 09:46:33,741 Processing page 7
2022-11-09 09:46:57,471 Processing page 8
2022-11-09 09:47:26,921 Processing page 9
2022-11-09 09:48:04,582 Processing page 10
2022-11-09 09:48:35,837 Processing page 11
2022-11-09 09:49:08,727 Processing page 12
2022-11-09 09:49:44,825 Processing page 13
2022-11-09 09:50:21,687 Processing page 14
2022-11-09 09:50:57,425 Processing page 15
2022-11-09 09:51:34,136 Processing page 16
2022-11-09 09:52:09,363 Processing page 17
2022-11-09 09:52:41,141 Processing page 18
2022-11-09 09:53:05,157 Processing page 19
2022-11-09 09:53:38,907 Processing page 20
2022-11-09 09:54:10,440 Processing page 21
2022-11-09 09:54:42,661 Processing page 22
--- Logging error ---
Traceback (most recent call last):
  File "/home/t-9adar/.conda/envs/env38/lib/python3.8/logging/__init__.py", line 1084, in emit
    stream.write(msg + self.terminator)
UnicodeEncodeError: 'latin-1' codec can't encode characters in position 39-43: ordinal not in range(256)
Call stack:
  File "/home/t-9adar/.conda/envs/env38/lib/python3.8/threading.py", line 890, in _bootstrap
    self._bootstrap_inner()
  File "/home/t-9adar/.conda/envs/env38/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/home/t-9adar/.conda/envs/env38/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/t-9adar/.conda/envs/env38/lib/python3.8/concurrent/futures/thread.py", line 80, in _worker
    work_item.run()
  File "/home/t-9adar/.conda/envs/env38/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "../parse_unsearchable_rolls/parser/parser.py", line 320, in get_data
    processed_box = self.process_boxes_text(text)
  File "../parse_unsearchable_rolls/parser/parser.py", line 149, in process_boxes_text
    result, last_key, is_splitted = self.columns_split(r, self.columns, result, last_key)
  File "../parse_unsearchable_rolls/parser/parser.py", line 255, in columns_split
    result, last_key, is_splitted = self.handle_separator_without_column(r, result, last_key)
  File "../parse_unsearchable_rolls/parser/parser.py", line 226, in handle_separator_without_column
    logging.warning(f'Split uncaught {r} {result}')
Message: "Split uncaught \u0d2a\u0d47\u0d30\u0d4d\u200c =) OrderedDict([('number', '575'), ('id', 'KL/01/005/324746')])"
Arguments: ()
2022-11-09 09:55:13,695 Split uncaught \u0d2a\u0d47\u0d30\u0d4d\u200c =) OrderedDict([('number', '575'), ('id', 'KL/01/005/324746')])
2022-11-09 09:55:19,062 Processing page 23
2022-11-09 09:55:55,709 Split uncaught Gale milesz? =p ef OrderedDict([('number', '611'), ('id', 'JWB2137834')])
2022-11-09 09:55:55,711 Processing page 24
2022-11-09 09:56:27,961 Processing page 25
2022-11-09 09:57:05,680 Processing page 26
2022-11-09 09:57:42,699 Processing page 27
2022-11-09 09:58:11,970 Processing page 28
2022-11-09 09:58:35,761 Processing page 29

#################
Epilogue Job Info:
Job ID: 467116[10].acropolis
User ID: t-9adar
Job Name: Kerala2015JobArray-10
Resource List: nodes=1:ppn=1,mem=3400mb,neednodes=1:ppn=1
Resources Used: cput=00:14:52,vmem=2346956kb,walltime=00:15:12,mem=1381112kb,energy_used=0
Exit Code: 271
#################

