2022-11-09 09:43:57,612 Converting data/part62/in/kerala/2015/2015_032_077.pdf to img...
2022-11-09 09:44:03,245 Parsing first and last page data..
2022-11-09 09:44:05,072 Detecting and parsing data/part62/in/kerala/2015/2015_032_077.pdf boxes..
2022-11-09 09:44:05,072 Processing page 3
2022-11-09 09:44:27,337 Processing page 4
2022-11-09 09:44:49,821 Processing page 5
2022-11-09 09:45:12,643 Processing page 6
2022-11-09 09:45:36,078 Processing page 7
2022-11-09 09:45:59,698 Processing page 8
2022-11-09 09:46:22,646 Processing page 9
2022-11-09 09:46:45,131 Processing page 10
2022-11-09 09:47:08,083 Processing page 11
2022-11-09 09:47:30,399 Processing page 12
2022-11-09 09:47:53,890 Processing page 13
2022-11-09 09:48:17,182 Processing page 14
2022-11-09 09:48:39,856 Processing page 15
2022-11-09 09:49:03,405 Processing page 16
2022-11-09 09:49:26,486 Processing page 17
2022-11-09 09:49:49,762 Processing page 18
2022-11-09 09:50:12,965 Processing page 19
2022-11-09 09:50:36,301 Processing page 20
2022-11-09 09:50:59,042 Processing page 21
2022-11-09 09:51:22,567 Processing page 22
--- Logging error ---
Traceback (most recent call last):
  File "/home/t-9adar/.conda/envs/env38/lib/python3.8/logging/__init__.py", line 1084, in emit
    stream.write(msg + self.terminator)
UnicodeEncodeError: 'latin-1' codec can't encode character '\u2019' in position 46: ordinal not in range(256)
Call stack:
  File "/home/t-9adar/.conda/envs/env38/lib/python3.8/threading.py", line 890, in _bootstrap
    self._bootstrap_inner()
  File "/home/t-9adar/.conda/envs/env38/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/home/t-9adar/.conda/envs/env38/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/t-9adar/.conda/envs/env38/lib/python3.8/concurrent/futures/thread.py", line 80, in _worker
    work_item.run()
  File "/home/t-9adar/.conda/envs/env38/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "../parse_unsearchable_rolls/parser/parser.py", line 320, in get_data
    processed_box = self.process_boxes_text(text)
  File "../parse_unsearchable_rolls/parser/parser.py", line 149, in process_boxes_text
    result, last_key, is_splitted = self.columns_split(r, self.columns, result, last_key)
  File "../parse_unsearchable_rolls/parser/parser.py", line 255, in columns_split
    result, last_key, is_splitted = self.handle_separator_without_column(r, result, last_key)
  File "../parse_unsearchable_rolls/parser/parser.py", line 226, in handle_separator_without_column
    logging.warning(f'Split uncaught {r} {result}')
Message: "Split uncaught algerie\u2019 alldieo> atomies OrderedDict([('number', '593'), ('id', 'KL/04/028/120329'), ('\u0d2a\u0d47\u0d30\u0d4d', 'ead'), ('\u0d35\u0d40\u0d1f\u0d4d\u0d1f\u0d41\u0d28\u0d2e\u0d4d\u0d2a\u0d30\u0d4d', '6/167 (0/195)')])"
Arguments: ()
2022-11-09 09:51:29,201 Split uncaught algerie\u2019 alldieo> atomies OrderedDict([('number', '593'), ('id', 'KL/04/028/120329'), ('\u0d2a\u0d47\u0d30\u0d4d', 'ead'), ('\u0d35\u0d40\u0d1f\u0d4d\u0d1f\u0d41\u0d28\u0d2e\u0d4d\u0d2a\u0d30\u0d4d', '6/167 (0/195)')])
2022-11-09 09:51:46,024 Processing page 23
2022-11-09 09:52:09,679 Processing page 24
2022-11-09 09:52:32,823 Processing page 25
2022-11-09 09:52:55,558 Processing page 26
2022-11-09 09:53:18,809 Processing page 27
2022-11-09 09:53:42,001 Processing page 28
2022-11-09 09:54:05,203 Processing page 29
2022-11-09 09:54:28,743 Processing page 30
2022-11-09 09:54:51,795 Processing page 31
--- Logging error ---
Traceback (most recent call last):
  File "/home/t-9adar/.conda/envs/env38/lib/python3.8/logging/__init__.py", line 1084, in emit
    stream.write(msg + self.terminator)
UnicodeEncodeError: 'latin-1' codec can't encode characters in position 39-40: ordinal not in range(256)
Call stack:
  File "/home/t-9adar/.conda/envs/env38/lib/python3.8/threading.py", line 890, in _bootstrap
    self._bootstrap_inner()
  File "/home/t-9adar/.conda/envs/env38/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/home/t-9adar/.conda/envs/env38/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/t-9adar/.conda/envs/env38/lib/python3.8/concurrent/futures/thread.py", line 80, in _worker
    work_item.run()
  File "/home/t-9adar/.conda/envs/env38/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "../parse_unsearchable_rolls/parser/parser.py", line 320, in get_data
    processed_box = self.process_boxes_text(text)
  File "../parse_unsearchable_rolls/parser/parser.py", line 149, in process_boxes_text
    result, last_key, is_splitted = self.columns_split(r, self.columns, result, last_key)
  File "../parse_unsearchable_rolls/parser/parser.py", line 255, in columns_split
    result, last_key, is_splitted = self.handle_separator_without_column(r, result, last_key)
  File "../parse_unsearchable_rolls/parser/parser.py", line 226, in handle_separator_without_column
    logging.warning(f'Split uncaught {r} {result}')
Message: "Split uncaught \u0d1f\u0d3f enilesz> OrderedDict([('number', '847'), ('id', 'WY00096552'), ('\u0d2a\u0d47\u0d30\u0d4d', '\u0d35\u0d3f\u0d28\u0d40\u0d24')])"
Arguments: ()
2022-11-09 09:55:10,555 Split uncaught \u0d1f\u0d3f enilesz> OrderedDict([('number', '847'), ('id', 'WY00096552'), ('\u0d2a\u0d47\u0d30\u0d4d', '\u0d35\u0d3f\u0d28\u0d40\u0d24')])
2022-11-09 09:55:14,431 Processing page 32
2022-11-09 09:55:37,947 Processing page 33
2022-11-09 09:56:01,329 Processing page 34
2022-11-09 09:56:25,193 Processing page 35
2022-11-09 09:56:49,232 Processing page 36
2022-11-09 09:57:13,231 Processing page 37
2022-11-09 09:57:37,350 Processing page 38
2022-11-09 09:58:02,439 Processing page 39
2022-11-09 09:58:26,126 Processing page 40
2022-11-09 09:58:50,214 Processing page 41

#################
Epilogue Job Info:
Job ID: 467116[62].acropolis
User ID: t-9adar
Job Name: Kerala2015JobArray-62
Resource List: nodes=1:ppn=1,mem=3400mb,neednodes=1:ppn=1
Resources Used: cput=00:14:59,vmem=2857452kb,walltime=00:15:16,mem=1897640kb,energy_used=0
Exit Code: 271
#################

