2022-11-09 09:44:20,703 Converting data/part223/in/kerala/2015/2015_113_110.pdf to img...
2022-11-09 09:44:28,936 Parsing first and last page data..
2022-11-09 09:44:33,079 Detecting and parsing data/part223/in/kerala/2015/2015_113_110.pdf boxes..
2022-11-09 09:44:33,080 Processing page 3
2022-11-09 09:45:11,089 Processing page 4
2022-11-09 09:45:48,612 Processing page 5
2022-11-09 09:46:25,520 Processing page 6
2022-11-09 09:47:02,562 Processing page 7
2022-11-09 09:47:40,989 Processing page 8
2022-11-09 09:48:19,638 Processing page 9
2022-11-09 09:48:57,750 Processing page 10
2022-11-09 09:49:35,525 Processing page 11
2022-11-09 09:50:15,360 Processing page 12
2022-11-09 09:50:52,154 Processing page 13
2022-11-09 09:51:30,975 Processing page 14
2022-11-09 09:52:09,549 Processing page 15
2022-11-09 09:52:49,268 Processing page 16
2022-11-09 09:53:28,682 Processing page 17
2022-11-09 09:54:07,815 Processing page 18
2022-11-09 09:54:44,665 Processing page 19
2022-11-09 09:55:21,966 Processing page 20
2022-11-09 09:55:59,714 Processing page 21
2022-11-09 09:56:36,773 Processing page 22
2022-11-09 09:57:15,592 Processing page 23
2022-11-09 09:57:53,440 Processing page 24
2022-11-09 09:58:30,607 Processing page 25
--- Logging error ---
Traceback (most recent call last):
  File "/home/t-9adar/.conda/envs/env38/lib/python3.8/logging/__init__.py", line 1084, in emit
    stream.write(msg + self.terminator)
UnicodeEncodeError: 'latin-1' codec can't encode characters in position 39-40: ordinal not in range(256)
Call stack:
  File "/home/t-9adar/.conda/envs/env38/lib/python3.8/threading.py", line 890, in _bootstrap
    self._bootstrap_inner()
  File "/home/t-9adar/.conda/envs/env38/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/home/t-9adar/.conda/envs/env38/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/t-9adar/.conda/envs/env38/lib/python3.8/concurrent/futures/thread.py", line 80, in _worker
    work_item.run()
  File "/home/t-9adar/.conda/envs/env38/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "../parse_unsearchable_rolls/parser/parser.py", line 320, in get_data
    processed_box = self.process_boxes_text(text)
  File "../parse_unsearchable_rolls/parser/parser.py", line 149, in process_boxes_text
    result, last_key, is_splitted = self.columns_split(r, self.columns, result, last_key)
  File "../parse_unsearchable_rolls/parser/parser.py", line 255, in columns_split
    result, last_key, is_splitted = self.handle_separator_without_column(r, result, last_key)
  File "../parse_unsearchable_rolls/parser/parser.py", line 226, in handle_separator_without_column
    logging.warning(f'Split uncaught {r} {result}')
Message: "Split uncaught \u0d2a\u0d3f Q20.21G08 af = OrderedDict([('number', '675'), ('id', '1020089698'), ('\u0d2a\u0d47\u0d30\u0d4d', '\u0d1c\u0d2f\u0d1a\u0d28\u0d4d\u0d26\u0d4d\u0d30\u0d28\u0d4d\\u200d \u0d2a\u0d3f \u0d06\u0d30\u0d4d\\u200d')])"
Arguments: ()
2022-11-09 09:58:52,223 Split uncaught \u0d2a\u0d3f Q20.21G08 af = OrderedDict([('number', '675'), ('id', '1020089698'), ('\u0d2a\u0d47\u0d30\u0d4d', '\u0d1c\u0d2f\u0d1a\u0d28\u0d4d\u0d26\u0d4d\u0d30\u0d28\u0d4d\u200d \u0d2a\u0d3f \u0d06\u0d30\u0d4d\u200d')])
2022-11-09 09:59:11,184 Processing page 26

#################
Epilogue Job Info:
Job ID: 467116[223].acropolis
User ID: t-9adar
Job Name: Kerala2015JobArray-223
Resource List: nodes=1:ppn=1,mem=3400mb,neednodes=1:ppn=1
Resources Used: cput=00:15:01,vmem=2267576kb,walltime=00:15:27,mem=1306864kb,energy_used=0
Exit Code: 271
#################

