2022-11-03 11:14:28,602 Converting data/part178/in/kerala/2016/2016_092_087.pdf to img...
2022-11-03 11:14:36,712 Parsing first and last page data..
2022-11-03 11:14:40,223 Detecting and parsing data/part178/in/kerala/2016/2016_092_087.pdf boxes..
2022-11-03 11:14:40,224 Processing page 3
2022-11-03 11:15:15,852 Processing page 4
2022-11-03 11:15:49,676 Processing page 5
2022-11-03 11:16:20,447 Processing page 6
2022-11-03 11:16:55,977 Processing page 7
2022-11-03 11:17:28,269 Processing page 8
2022-11-03 11:18:01,485 Processing page 9
2022-11-03 11:18:37,212 Processing page 10
2022-11-03 11:19:12,783 Processing page 11
2022-11-03 11:19:47,361 Processing page 12
2022-11-03 11:20:21,840 Processing page 13
--- Logging error ---
Traceback (most recent call last):
  File "/home/t-9adar/.conda/envs/env38/lib/python3.8/logging/__init__.py", line 1084, in emit
    stream.write(msg + self.terminator)
UnicodeEncodeError: 'latin-1' codec can't encode characters in position 39-43: ordinal not in range(256)
Call stack:
  File "/home/t-9adar/.conda/envs/env38/lib/python3.8/threading.py", line 890, in _bootstrap
    self._bootstrap_inner()
  File "/home/t-9adar/.conda/envs/env38/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/home/t-9adar/.conda/envs/env38/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/t-9adar/.conda/envs/env38/lib/python3.8/concurrent/futures/thread.py", line 80, in _worker
    work_item.run()
  File "/home/t-9adar/.conda/envs/env38/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "../parse_unsearchable_rolls/parser/parser.py", line 320, in get_data
    processed_box = self.process_boxes_text(text)
  File "../parse_unsearchable_rolls/parser/parser.py", line 149, in process_boxes_text
    result, last_key, is_splitted = self.columns_split(r, self.columns, result, last_key)
  File "../parse_unsearchable_rolls/parser/parser.py", line 255, in columns_split
    result, last_key, is_splitted = self.handle_separator_without_column(r, result, last_key)
  File "../parse_unsearchable_rolls/parser/parser.py", line 226, in handle_separator_without_column
    logging.warning(f'Split uncaught {r} {result}')
Message: "Split uncaught \u0d2a\u0d47\u0d30\u0d4d\u200c =) OrderedDict([('number', '308'), ('id', 'KL/14/086/030408')])"
Arguments: ()
2022-11-03 11:20:47,488 Split uncaught \u0d2a\u0d47\u0d30\u0d4d\u200c =) OrderedDict([('number', '308'), ('id', 'KL/14/086/030408')])
2022-11-03 11:20:51,150 Processing page 14
2022-11-03 11:21:26,818 Processing page 15
2022-11-03 11:22:02,199 Processing page 16
2022-11-03 11:22:39,137 Processing page 17
2022-11-03 11:23:13,416 Processing page 18
2022-11-03 11:23:49,414 Processing page 19
2022-11-03 11:24:23,943 Processing page 20
2022-11-03 11:24:59,378 Processing page 21
2022-11-03 11:25:33,733 Processing page 22
2022-11-03 11:26:09,238 Processing page 23
2022-11-03 11:26:44,315 Processing page 24
2022-11-03 11:27:19,026 Processing page 25
2022-11-03 11:27:52,249 Processing page 26
2022-11-03 11:28:28,315 Processing page 27
2022-11-03 11:29:03,347 Processing page 28
--- Logging error ---
Traceback (most recent call last):
  File "/home/t-9adar/.conda/envs/env38/lib/python3.8/logging/__init__.py", line 1084, in emit
    stream.write(msg + self.terminator)
UnicodeEncodeError: 'latin-1' codec can't encode characters in position 39-40: ordinal not in range(256)
Call stack:
  File "/home/t-9adar/.conda/envs/env38/lib/python3.8/threading.py", line 890, in _bootstrap
    self._bootstrap_inner()
  File "/home/t-9adar/.conda/envs/env38/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/home/t-9adar/.conda/envs/env38/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/t-9adar/.conda/envs/env38/lib/python3.8/concurrent/futures/thread.py", line 80, in _worker
    work_item.run()
  File "/home/t-9adar/.conda/envs/env38/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "../parse_unsearchable_rolls/parser/parser.py", line 320, in get_data
    processed_box = self.process_boxes_text(text)
  File "../parse_unsearchable_rolls/parser/parser.py", line 149, in process_boxes_text
    result, last_key, is_splitted = self.columns_split(r, self.columns, result, last_key)
  File "../parse_unsearchable_rolls/parser/parser.py", line 255, in columns_split
    result, last_key, is_splitted = self.handle_separator_without_column(r, result, last_key)
  File "../parse_unsearchable_rolls/parser/parser.py", line 226, in handle_separator_without_column
    logging.warning(f'Split uncaught {r} {result}')
Message: "Split uncaught \u0d28\u0d3f A>SJULHYM AG OrderedDict([('number', '765'), ('id', 'SVC0555466'), ('\u0d2a\u0d47\u0d30\u0d4d', '\u0d1a\u0d3e\u0d15\u0d4d\u0d15\u0d4b\u0d1a\u0d4d\u0d1a\u0d28\u0d4d\\u200d'), ('\u0d05\u0d1a\u0d4d\u0d1b\u0d28\u0d4d\u0d31\u0d46 \u0d2a\u0d47\u0d30\u0d4d', 'agm')])"
Arguments: ()
2022-11-03 11:29:27,108 Split uncaught \u0d28\u0d3f A>SJULHYM AG OrderedDict([('number', '765'), ('id', 'SVC0555466'), ('\u0d2a\u0d47\u0d30\u0d4d', '\u0d1a\u0d3e\u0d15\u0d4d\u0d15\u0d4b\u0d1a\u0d4d\u0d1a\u0d28\u0d4d\u200d'), ('\u0d05\u0d1a\u0d4d\u0d1b\u0d28\u0d4d\u0d31\u0d46 \u0d2a\u0d47\u0d30\u0d4d', 'agm')])
2022-11-03 11:29:37,891 Processing page 29
2022-11-03 11:30:13,264 Processing page 30
2022-11-03 11:30:47,282 Processing page 31
--- Logging error ---
Traceback (most recent call last):
  File "/home/t-9adar/.conda/envs/env38/lib/python3.8/logging/__init__.py", line 1084, in emit
    stream.write(msg + self.terminator)
UnicodeEncodeError: 'latin-1' codec can't encode characters in position 39-43: ordinal not in range(256)
Call stack:
  File "/home/t-9adar/.conda/envs/env38/lib/python3.8/threading.py", line 890, in _bootstrap
    self._bootstrap_inner()
  File "/home/t-9adar/.conda/envs/env38/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/home/t-9adar/.conda/envs/env38/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/t-9adar/.conda/envs/env38/lib/python3.8/concurrent/futures/thread.py", line 80, in _worker
    work_item.run()
  File "/home/t-9adar/.conda/envs/env38/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "../parse_unsearchable_rolls/parser/parser.py", line 320, in get_data
    processed_box = self.process_boxes_text(text)
  File "../parse_unsearchable_rolls/parser/parser.py", line 149, in process_boxes_text
    result, last_key, is_splitted = self.columns_split(r, self.columns, result, last_key)
  File "../parse_unsearchable_rolls/parser/parser.py", line 255, in columns_split
    result, last_key, is_splitted = self.handle_separator_without_column(r, result, last_key)
  File "../parse_unsearchable_rolls/parser/parser.py", line 226, in handle_separator_without_column
    logging.warning(f'Split uncaught {r} {result}')
Message: "Split uncaught \u0d2a\u0d47\u0d30\u0d4d\u200c =) OrderedDict([('number', '845'), ('id', 'GKH1262120')])"
Arguments: ()
2022-11-03 11:31:19,687 Split uncaught \u0d2a\u0d47\u0d30\u0d4d\u200c =) OrderedDict([('number', '845'), ('id', 'GKH1262120')])
2022-11-03 11:31:22,694 Processing page 32
2022-11-03 11:31:56,696 Processing page 33
2022-11-03 11:32:31,410 Processing page 34
2022-11-03 11:33:05,637 Processing page 35
2022-11-03 11:33:40,008 Processing page 36
2022-11-03 11:34:15,352 Processing page 37
2022-11-03 11:34:50,473 Processing page 38
2022-11-03 11:35:26,686 Processing page 39
2022-11-03 11:36:02,561 Processing page 40
2022-11-03 11:36:39,284 Processing page 41
2022-11-03 11:37:15,355 Processing page 42
2022-11-03 11:37:50,303 Processing page 43
2022-11-03 11:38:24,769 Processing page 44
2022-11-03 11:38:59,866 Processing page 45
/share/svasudevan2lab/gs-delhi/parse_unsearchable_rolls/scripts/kerala/joblist_2016/kerala178.sh: line 1: 36619 Killed                  python scripts/kerala/kerala_2016.py data/part178/

#################
Epilogue Job Info:
Job ID: 466350[178].acropolis
User ID: t-9adar
Job Name: Kerala2016JobArray-178
Resource List: nodes=1:ppn=1,mem=2gb,neednodes=1:ppn=1
Resources Used: cput=00:24:21,vmem=3433460kb,walltime=00:24:47,mem=2027660kb,energy_used=0
Exit Code: 137
Exit code 137 job terminated, resource limit violation
Generally this means you need to request more RAM or CPU
Please compare your resources used/requested
#################

