2022-11-03 11:14:37,034 Converting data/part135/in/kerala/2016/2016_070_129.pdf to img...
2022-11-03 11:14:47,151 Parsing first and last page data..
2022-11-03 11:14:57,505 Detecting and parsing data/part135/in/kerala/2016/2016_070_129.pdf boxes..
2022-11-03 11:14:57,507 Processing page 3
2022-11-03 11:15:30,677 Processing page 4
--- Logging error ---
Traceback (most recent call last):
  File "/home/t-9adar/.conda/envs/env38/lib/python3.8/logging/__init__.py", line 1084, in emit
    stream.write(msg + self.terminator)
UnicodeEncodeError: 'latin-1' codec can't encode character '\u2019' in position 43: ordinal not in range(256)
Call stack:
  File "/home/t-9adar/.conda/envs/env38/lib/python3.8/threading.py", line 890, in _bootstrap
    self._bootstrap_inner()
  File "/home/t-9adar/.conda/envs/env38/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/home/t-9adar/.conda/envs/env38/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/t-9adar/.conda/envs/env38/lib/python3.8/concurrent/futures/thread.py", line 80, in _worker
    work_item.run()
  File "/home/t-9adar/.conda/envs/env38/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "../parse_unsearchable_rolls/parser/parser.py", line 320, in get_data
    processed_box = self.process_boxes_text(text)
  File "../parse_unsearchable_rolls/parser/parser.py", line 149, in process_boxes_text
    result, last_key, is_splitted = self.columns_split(r, self.columns, result, last_key)
  File "../parse_unsearchable_rolls/parser/parser.py", line 255, in columns_split
    result, last_key, is_splitted = self.handle_separator_without_column(r, result, last_key)
  File "../parse_unsearchable_rolls/parser/parser.py", line 226, in handle_separator_without_column
    logging.warning(f'Split uncaught {r} {result}')
Message: "Split uncaught Gale\u2019 Ook OIE AELIQIA>O OrderedDict([('number', '52'), ('id', 'UAZ0399873')])"
Arguments: ()
2022-11-03 11:15:46,887 Split uncaught Gale\u2019 Ook OIE AELIQIA>O OrderedDict([('number', '52'), ('id', 'UAZ0399873')])
2022-11-03 11:16:05,239 Processing page 5
2022-11-03 11:16:39,225 Processing page 6
2022-11-03 11:17:14,844 Processing page 7
2022-11-03 11:17:49,725 Processing page 8
2022-11-03 11:18:24,222 Processing page 9
2022-11-03 11:18:59,091 Processing page 10
2022-11-03 11:19:34,741 Processing page 11
2022-11-03 11:20:10,668 Processing page 12
2022-11-03 11:20:45,531 Processing page 13
2022-11-03 11:21:20,750 Processing page 14
2022-11-03 11:21:56,021 Processing page 15
2022-11-03 11:22:32,283 Processing page 16
2022-11-03 11:23:08,315 Processing page 17
2022-11-03 11:23:44,150 Processing page 18
2022-11-03 11:24:19,557 Processing page 19
2022-11-03 11:24:55,294 Processing page 20
2022-11-03 11:25:31,095 Processing page 21
2022-11-03 11:26:06,450 Processing page 22
2022-11-03 11:26:40,659 Processing page 23
2022-11-03 11:27:15,789 Processing page 24
2022-11-03 11:27:50,887 Processing page 25
2022-11-03 11:28:26,461 Processing page 26
2022-11-03 11:29:01,149 Processing page 27
2022-11-03 11:29:38,079 Processing page 28
2022-11-03 11:29:55,844 Split uncaught Gale mile> OrderedDict([('number', '76'), ('id', 'MVP1681261')])
2022-11-03 11:30:13,635 Processing page 29
2022-11-03 11:30:49,183 Processing page 30
2022-11-03 11:31:25,860 Processing page 31
2022-11-03 11:32:01,168 Processing page 32
2022-11-03 11:32:37,310 Processing page 33
2022-11-03 11:33:13,735 Processing page 34
2022-11-03 11:33:50,658 Processing page 35
--- Logging error ---
Traceback (most recent call last):
  File "/home/t-9adar/.conda/envs/env38/lib/python3.8/logging/__init__.py", line 1084, in emit
    stream.write(msg + self.terminator)
UnicodeEncodeError: 'latin-1' codec can't encode characters in position 39-43: ordinal not in range(256)
Call stack:
  File "/home/t-9adar/.conda/envs/env38/lib/python3.8/threading.py", line 890, in _bootstrap
    self._bootstrap_inner()
  File "/home/t-9adar/.conda/envs/env38/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/home/t-9adar/.conda/envs/env38/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/t-9adar/.conda/envs/env38/lib/python3.8/concurrent/futures/thread.py", line 80, in _worker
    work_item.run()
  File "/home/t-9adar/.conda/envs/env38/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "../parse_unsearchable_rolls/parser/parser.py", line 320, in get_data
    processed_box = self.process_boxes_text(text)
  File "../parse_unsearchable_rolls/parser/parser.py", line 149, in process_boxes_text
    result, last_key, is_splitted = self.columns_split(r, self.columns, result, last_key)
  File "../parse_unsearchable_rolls/parser/parser.py", line 255, in columns_split
    result, last_key, is_splitted = self.handle_separator_without_column(r, result, last_key)
  File "../parse_unsearchable_rolls/parser/parser.py", line 226, in handle_separator_without_column
    logging.warning(f'Split uncaught {r} {result}')
Message: "Split uncaught \u0d2a\u0d47\u0d30\u0d4d\u200c =) OrderedDict([('number', '986'), ('id', 'MVP1343987')])"
Arguments: ()
2022-11-03 11:34:00,252 Split uncaught \u0d2a\u0d47\u0d30\u0d4d\u200c =) OrderedDict([('number', '986'), ('id', 'MVP1343987')])
2022-11-03 11:34:26,455 Processing page 36
2022-11-03 11:35:01,645 Processing page 37
2022-11-03 11:35:37,665 Processing page 38
2022-11-03 11:36:15,903 Processing page 39
2022-11-03 11:36:52,564 Processing page 40
2022-11-03 11:37:29,361 Processing page 41
2022-11-03 11:38:04,903 Processing page 42
2022-11-03 11:38:41,116 Processing page 43
2022-11-03 11:39:17,038 Processing page 44
/share/svasudevan2lab/gs-delhi/parse_unsearchable_rolls/scripts/kerala/joblist_2016/kerala135.sh: line 1:  1602 Killed                  python scripts/kerala/kerala_2016.py data/part135/

#################
Epilogue Job Info:
Job ID: 466350[135].acropolis
User ID: t-9adar
Job Name: Kerala2016JobArray-135
Resource List: nodes=1:ppn=1,mem=2gb,neednodes=1:ppn=1
Resources Used: cput=00:23:57,vmem=3437408kb,walltime=00:25:08,mem=2069324kb,energy_used=0
Exit Code: 137
Exit code 137 job terminated, resource limit violation
Generally this means you need to request more RAM or CPU
Please compare your resources used/requested
#################

