2022-11-03 11:14:37,721 Converting data/part141/in/kerala/2016/2016_073_109.pdf to img...
2022-11-03 11:14:47,204 Parsing first and last page data..
2022-11-03 11:14:57,452 Detecting and parsing data/part141/in/kerala/2016/2016_073_109.pdf boxes..
2022-11-03 11:14:57,452 Processing page 3
2022-11-03 11:15:32,235 Processing page 4
2022-11-03 11:16:06,118 Processing page 5
2022-11-03 11:16:39,820 Processing page 6
2022-11-03 11:17:14,436 Processing page 7
2022-11-03 11:17:48,605 Processing page 8
2022-11-03 11:18:22,994 Processing page 9
2022-11-03 11:18:58,476 Processing page 10
2022-11-03 11:19:33,156 Processing page 11
2022-11-03 11:20:07,445 Processing page 12
2022-11-03 11:20:42,311 Processing page 13
2022-11-03 11:21:18,220 Processing page 14
2022-11-03 11:21:52,808 Processing page 15
2022-11-03 11:22:28,462 Processing page 16
2022-11-03 11:23:02,925 Processing page 17
2022-11-03 11:23:37,566 Processing page 18
2022-11-03 11:24:12,035 Processing page 19
2022-11-03 11:24:46,201 Processing page 20
2022-11-03 11:25:01,303 Processing page 21
2022-11-03 11:25:35,504 Processing page 22
2022-11-03 11:26:09,741 Processing page 23
2022-11-03 11:26:43,558 Processing page 24
2022-11-03 11:27:17,346 Processing page 25
2022-11-03 11:27:52,322 Processing page 26
2022-11-03 11:28:27,356 Processing page 27
2022-11-03 11:29:01,650 Processing page 28
2022-11-03 11:29:35,643 Processing page 29
2022-11-03 11:30:09,377 Processing page 30
2022-11-03 11:30:43,895 Processing page 31
--- Logging error ---
Traceback (most recent call last):
  File "/home/t-9adar/.conda/envs/env38/lib/python3.8/logging/__init__.py", line 1084, in emit
    stream.write(msg + self.terminator)
UnicodeEncodeError: 'latin-1' codec can't encode characters in position 122-129: ordinal not in range(256)
Call stack:
  File "/home/t-9adar/.conda/envs/env38/lib/python3.8/threading.py", line 890, in _bootstrap
    self._bootstrap_inner()
  File "/home/t-9adar/.conda/envs/env38/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/home/t-9adar/.conda/envs/env38/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/t-9adar/.conda/envs/env38/lib/python3.8/concurrent/futures/thread.py", line 80, in _worker
    work_item.run()
  File "/home/t-9adar/.conda/envs/env38/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "../parse_unsearchable_rolls/parser/parser.py", line 320, in get_data
    processed_box = self.process_boxes_text(text)
  File "../parse_unsearchable_rolls/parser/parser.py", line 149, in process_boxes_text
    result, last_key, is_splitted = self.columns_split(r, self.columns, result, last_key)
  File "../parse_unsearchable_rolls/parser/parser.py", line 255, in columns_split
    result, last_key, is_splitted = self.handle_separator_without_column(r, result, last_key)
  File "../parse_unsearchable_rolls/parser/parser.py", line 226, in handle_separator_without_column
    logging.warning(f'Split uncaught {r} {result}')
Message: "Split uncaught allgysnie OOA>Bo POO OrderedDict([('number', '835'), ('id', 'KL/10/062/429128'), ('\u0d05\u0d1a\u0d4d\u0d1b\u0d28\u0d4d\u0d31\u0d46 \u0d2a\u0d47\u0d30\u0d4d', '\u0d35\u0d47\u0d32\u0d3e\u0d2f\u0d41\u0d27\u0d28\u0d4d\\u200d')])"
Arguments: ()
2022-11-03 11:31:09,709 Split uncaught allgysnie OOA>Bo POO OrderedDict([('number', '835'), ('id', 'KL/10/062/429128'), ('\u0d05\u0d1a\u0d4d\u0d1b\u0d28\u0d4d\u0d31\u0d46 \u0d2a\u0d47\u0d30\u0d4d', '\u0d35\u0d47\u0d32\u0d3e\u0d2f\u0d41\u0d27\u0d28\u0d4d\u200d')])
2022-11-03 11:31:19,143 Processing page 32
2022-11-03 11:31:53,155 Processing page 33
2022-11-03 11:32:27,179 Processing page 34
2022-11-03 11:33:00,690 Processing page 35
--- Logging error ---
Traceback (most recent call last):
  File "/home/t-9adar/.conda/envs/env38/lib/python3.8/logging/__init__.py", line 1084, in emit
    stream.write(msg + self.terminator)
UnicodeEncodeError: 'latin-1' codec can't encode characters in position 39-40: ordinal not in range(256)
Call stack:
  File "/home/t-9adar/.conda/envs/env38/lib/python3.8/threading.py", line 890, in _bootstrap
    self._bootstrap_inner()
  File "/home/t-9adar/.conda/envs/env38/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/home/t-9adar/.conda/envs/env38/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/t-9adar/.conda/envs/env38/lib/python3.8/concurrent/futures/thread.py", line 80, in _worker
    work_item.run()
  File "/home/t-9adar/.conda/envs/env38/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "../parse_unsearchable_rolls/parser/parser.py", line 320, in get_data
    processed_box = self.process_boxes_text(text)
  File "../parse_unsearchable_rolls/parser/parser.py", line 149, in process_boxes_text
    result, last_key, is_splitted = self.columns_split(r, self.columns, result, last_key)
  File "../parse_unsearchable_rolls/parser/parser.py", line 255, in columns_split
    result, last_key, is_splitted = self.handle_separator_without_column(r, result, last_key)
  File "../parse_unsearchable_rolls/parser/parser.py", line 226, in handle_separator_without_column
    logging.warning(f'Split uncaught {r} {result}')
Message: "Split uncaught \u0d1f\u0d3f milen> OrderedDict([('number', '966'), ('id', 'VADUTERY')])"
Arguments: ()
2022-11-03 11:33:16,534 Split uncaught \u0d1f\u0d3f milen> OrderedDict([('number', '966'), ('id', 'VADUTERY')])
2022-11-03 11:33:34,586 Processing page 36
2022-11-03 11:34:08,645 Processing page 37
2022-11-03 11:34:44,532 Processing page 38
2022-11-03 11:35:18,557 Processing page 39
2022-11-03 11:35:52,752 Processing page 40
2022-11-03 11:36:28,171 Processing page 41
2022-11-03 11:37:01,889 Processing page 42
2022-11-03 11:37:36,367 Processing page 43
/share/svasudevan2lab/gs-delhi/parse_unsearchable_rolls/scripts/kerala/joblist_2016/kerala141.sh: line 1:  1815 Killed                  python scripts/kerala/kerala_2016.py data/part141/

#################
Epilogue Job Info:
Job ID: 466350[141].acropolis
User ID: t-9adar
Job Name: Kerala2016JobArray-141
Resource List: nodes=1:ppn=1,mem=2gb,neednodes=1:ppn=1
Resources Used: cput=00:22:17,vmem=3398204kb,walltime=00:23:26,mem=2004992kb,energy_used=0
Exit Code: 137
Exit code 137 job terminated, resource limit violation
Generally this means you need to request more RAM or CPU
Please compare your resources used/requested
#################

