2022-11-03 11:14:40,197 Converting data/part107/in/kerala/2016/2016_056_063.pdf to img...
2022-11-03 11:14:49,006 Parsing first and last page data..
2022-11-03 11:15:04,884 Detecting and parsing data/part107/in/kerala/2016/2016_056_063.pdf boxes..
2022-11-03 11:15:04,884 Processing page 3
2022-11-03 11:15:43,228 Processing page 4
2022-11-03 11:16:19,537 Processing page 5
2022-11-03 11:16:55,403 Processing page 6
2022-11-03 11:17:31,993 Processing page 7
2022-11-03 11:18:09,499 Processing page 8
--- Logging error ---
Traceback (most recent call last):
  File "/home/t-9adar/.conda/envs/env38/lib/python3.8/logging/__init__.py", line 1084, in emit
    stream.write(msg + self.terminator)
UnicodeEncodeError: 'latin-1' codec can't encode character '\u0d67' in position 106: ordinal not in range(256)
Call stack:
  File "/home/t-9adar/.conda/envs/env38/lib/python3.8/threading.py", line 890, in _bootstrap
    self._bootstrap_inner()
  File "/home/t-9adar/.conda/envs/env38/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/home/t-9adar/.conda/envs/env38/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/t-9adar/.conda/envs/env38/lib/python3.8/concurrent/futures/thread.py", line 80, in _worker
    work_item.run()
  File "/home/t-9adar/.conda/envs/env38/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "../parse_unsearchable_rolls/parser/parser.py", line 320, in get_data
    processed_box = self.process_boxes_text(text)
  File "../parse_unsearchable_rolls/parser/parser.py", line 149, in process_boxes_text
    result, last_key, is_splitted = self.columns_split(r, self.columns, result, last_key)
  File "../parse_unsearchable_rolls/parser/parser.py", line 255, in columns_split
    result, last_key, is_splitted = self.handle_separator_without_column(r, result, last_key)
  File "../parse_unsearchable_rolls/parser/parser.py", line 226, in handle_separator_without_column
    logging.warning(f'Split uncaught {r} {result}')
Message: "Split uncaught adomalog cud mileg> M1 ag) OrderedDict([('number', '151'), ('id', '\u0d67100314369'), ('\u0d2a\u0d47\u0d30\u0d4d', '\u0d28\u0d4d\u0d26\u0d3f\u0d2e\u0d4d\u0d2e\u0d3f')])"
Arguments: ()
2022-11-03 11:18:47,581 Split uncaught adomalog cud mileg> M1 ag) OrderedDict([('number', '151'), ('id', '\u0d67100314369'), ('\u0d2a\u0d47\u0d30\u0d4d', '\u0d28\u0d4d\u0d26\u0d3f\u0d2e\u0d4d\u0d2e\u0d3f')])
2022-11-03 11:18:47,938 Processing page 9
2022-11-03 11:19:23,963 Processing page 10
2022-11-03 11:20:00,358 Processing page 11
2022-11-03 11:20:36,742 Processing page 12
2022-11-03 11:21:14,096 Processing page 13
2022-11-03 11:21:50,947 Processing page 14
2022-11-03 11:22:27,728 Processing page 15
2022-11-03 11:23:04,094 Processing page 16
2022-11-03 11:23:41,102 Processing page 17
2022-11-03 11:24:17,836 Processing page 18
2022-11-03 11:24:54,658 Processing page 19
2022-11-03 11:25:31,820 Processing page 20
2022-11-03 11:26:08,519 Processing page 21
2022-11-03 11:26:45,379 Processing page 22
2022-11-03 11:27:21,018 Processing page 23
2022-11-03 11:27:57,930 Processing page 24
2022-11-03 11:28:36,036 Processing page 25
2022-11-03 11:29:13,411 Processing page 26
2022-11-03 11:29:50,032 Processing page 27
2022-11-03 11:30:27,069 Processing page 28
--- Logging error ---
Traceback (most recent call last):
  File "/home/t-9adar/.conda/envs/env38/lib/python3.8/logging/__init__.py", line 1084, in emit
    stream.write(msg + self.terminator)
UnicodeEncodeError: 'latin-1' codec can't encode characters in position 39-40: ordinal not in range(256)
Call stack:
  File "/home/t-9adar/.conda/envs/env38/lib/python3.8/threading.py", line 890, in _bootstrap
    self._bootstrap_inner()
  File "/home/t-9adar/.conda/envs/env38/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/home/t-9adar/.conda/envs/env38/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/t-9adar/.conda/envs/env38/lib/python3.8/concurrent/futures/thread.py", line 80, in _worker
    work_item.run()
  File "/home/t-9adar/.conda/envs/env38/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "../parse_unsearchable_rolls/parser/parser.py", line 320, in get_data
    processed_box = self.process_boxes_text(text)
  File "../parse_unsearchable_rolls/parser/parser.py", line 149, in process_boxes_text
    result, last_key, is_splitted = self.columns_split(r, self.columns, result, last_key)
  File "../parse_unsearchable_rolls/parser/parser.py", line 255, in columns_split
    result, last_key, is_splitted = self.handle_separator_without_column(r, result, last_key)
  File "../parse_unsearchable_rolls/parser/parser.py", line 226, in handle_separator_without_column
    logging.warning(f'Split uncaught {r} {result}')
Message: "Split uncaught \u0d1f\u0d3f \u0d2a\u0d4d\u0d2a\u0d3f COM > OrderedDict([('number', '7716'), ('id', 'LWW2009157'), ('\u0d2a\u0d47\u0d30\u0d4d', '\u0d15\u0d4c\u0d38\u0d32\u0d4d\u0d2f \u0d0e\u0d02')])"
Arguments: ()
2022-11-03 11:30:37,094 Split uncaught \u0d1f\u0d3f \u0d2a\u0d4d\u0d2a\u0d3f COM > OrderedDict([('number', '7716'), ('id', 'LWW2009157'), ('\u0d2a\u0d47\u0d30\u0d4d', '\u0d15\u0d4c\u0d38\u0d32\u0d4d\u0d2f \u0d0e\u0d02')])
2022-11-03 11:31:04,246 Processing page 29
2022-11-03 11:31:42,780 Processing page 30
2022-11-03 11:32:20,691 Processing page 31
2022-11-03 11:32:58,634 Processing page 32
2022-11-03 11:33:37,026 Processing page 33
2022-11-03 11:34:14,315 Processing page 34
2022-11-03 11:34:52,146 Processing page 35
2022-11-03 11:35:29,195 Processing page 36
2022-11-03 11:36:07,032 Processing page 37
2022-11-03 11:36:44,272 Processing page 38
2022-11-03 11:37:23,660 Processing page 39
2022-11-03 11:38:02,941 Processing page 40
2022-11-03 11:38:41,334 Processing page 41
2022-11-03 11:39:19,474 Processing page 42
2022-11-03 11:39:47,085 Processing page 43
2022-11-03 11:40:12,004 Processing page 44
2022-11-03 11:40:17,308 Processing page 45
/share/svasudevan2lab/gs-delhi/parse_unsearchable_rolls/scripts/kerala/joblist_2016/kerala107.sh: line 1: 56116 Killed                  python scripts/kerala/kerala_2016.py data/part107/

#################
Epilogue Job Info:
Job ID: 466350[107].acropolis
User ID: t-9adar
Job Name: Kerala2016JobArray-107
Resource List: nodes=1:ppn=1,mem=2gb,neednodes=1:ppn=1
Resources Used: cput=00:24:52,vmem=3417756kb,walltime=00:26:10,mem=2018864kb,energy_used=0
Exit Code: 137
Exit code 137 job terminated, resource limit violation
Generally this means you need to request more RAM or CPU
Please compare your resources used/requested
#################

